# Generated by Django 5.0.3 on 2024-03-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.rooms_type'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='capacity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.capacity'),
            preserve_default=False,
        ),
    ]
