# Generated by Django 5.0.3 on 2024-03-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_capacity_remove_rooms_capacity_alter_rooms_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='capacity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='room.capacity'),
        ),
    ]
